# Simple LSTM
### Importing

In [2]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM, Dense   

### method

In [19]:
def split_sequence(sequence, n_step):
   x,y = list(), list() #x is data and y is label
   for i in range(len(sequence)):
       end_ix = i + n_step
   
       if end_ix > len(sequence) - 1: # In this -if- we want if data be beyond len(sequence)-1, the command will not continue and break..
          break
       seq_x, seq_y = sequence[i:end_ix] , sequence[end_ix]   
       x.append(seq_x)
       y.append(seq_y)
   return array(x) , array(y)

- making data x , y

In [20]:
n_steps = 3 #timestep or look_up
seq_value = [10,20,30,40,50,60,70,80,90]
   
x,y = split_sequence(seq_value , n_steps)

for i in range(len(x)):   
   print(x[i],y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [24]:
print(x.shape)
print(y.shape)

(6, 3)
(6,)


### training model
- vinila lstm

In [31]:
#The input must be three-dimensional or three-channel, that's why we reshape it
n_features = 1 
x = x.reshape(x.shape[0],x.shape[1],n_features) 
x.shape

(6, 3, 1)

In [39]:
model = Sequential()
model.add(LSTM(100, activation = 'relu', input_shape=(n_steps,n_features)))  

model.add(Dense(1)) #n-output  
   
model.compile(optimizer='adam',loss='mse')   
model.fit(x,y,epochs=200,verbose=1) #verbose is the choice that how you want to see the output of your Nural Network while it's training. If you set verbose = 0, It will show nothing

Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 4504.0923
Epoch 2/200
1/1 [==============================] - 0s 9ms/step - loss: 4368.3706
Epoch 3/200
1/1 [==============================] - 0s 8ms/step - loss: 4231.6294
Epoch 4/200
1/1 [==============================] - 0s 15ms/step - loss: 4093.3274
Epoch 5/200
1/1 [==============================] - 0s 12ms/step - loss: 3952.8601
Epoch 6/200
1/1 [==============================] - 0s 9ms/step - loss: 3809.5371
Epoch 7/200
1/1 [==============================] - 0s 10ms/step - loss: 3662.5657
Epoch 8/200
1/1 [==============================] - 0s 9ms/step - loss: 3511.0183
Epoch 9/200
1/1 [==============================] - 0s 10ms/step - loss: 3353.8792
Epoch 10/200
1/1 [==============================] - 0s 8ms/step - loss: 3190.1379
Epoch 11/200
1/1 [==============================] - 0s 8ms/step - loss: 3018.9177
Epoch 12/200
1/1 [==============================] - 0s 9ms/step - loss: 2839.6292
Epoch 13/200
1/1 [====

### testing

In [54]:
x_input = array([20,30,40])
x_input = x_input.reshape(1,n_steps,n_features)

In [55]:
x_input.shape

(1, 3, 1)

In [56]:
yhat = model.predict(x_input, verbose=0)
print('predicted:',yhat)
print('real:',y[1])

predicted: [[50.773876]]
real: 50
