# Multiple-Input-LSTM
## Developer: mehdi sahraei
### Importing

In [2]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM, Dense        
from numpy import hstack

### method

In [4]:
def split_sequence(sequence, n_step):
   x,y = list(), list() #x is data and y is label
   for i in range(len(sequence)):
       end_ix = i + n_step
   
       if end_ix > len(sequence) - 1: # In this -if- we want if data be beyond len(sequence)-1, the command will not continue and break.
          break
       seq_x, seq_y = sequence[i:end_ix,:] , sequence[end_ix,:] # whole column
       x.append(seq_x)
       y.append(seq_y)
   return array(x) , array(y)

- making data x , y

In [24]:

seq1 = array([10,20,30,40,50,60,70,80,90])
seq2 = array([10,20,30,40,50,60,70,80,90])
seq3 = array([10,20,30,40,50,60,70,80,90])
   

seq1 = seq1.reshape((len(seq1),1)) #reshape: (9, 1)
seq2 = seq2.reshape((len(seq2),1)) #reshape: (9, 1)
seq3 = seq3.reshape((len(seq3),1)) #reshape: (9, 1)


dataset = hstack((seq1,seq2,seq3)) #function is used to stack the sequence of input arrays horizontally
dataset

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [40, 40, 40],
       [50, 50, 50],
       [60, 60, 60],
       [70, 70, 70],
       [80, 80, 80],
       [90, 90, 90]])

In [29]:
print('-'*75) #print -----


n_steps = 3 #timestep or look_up
x,y = split_sequence(dataset, n_steps)
print(x.shape,y.shape)   
   
for i in range(len(x)):
   print(x[i],y[i])
   

---------------------------------------------------------------------------
(6, 3, 3) (6, 3)
[[10 10 10]
 [20 20 20]
 [30 30 30]] [40 40 40]
[[20 20 20]
 [30 30 30]
 [40 40 40]] [50 50 50]
[[30 30 30]
 [40 40 40]
 [50 50 50]] [60 60 60]
[[40 40 40]
 [50 50 50]
 [60 60 60]] [70 70 70]
[[50 50 50]
 [60 60 60]
 [70 70 70]] [80 80 80]
[[60 60 60]
 [70 70 70]
 [80 80 80]] [90 90 90]


### training model
- stack lstm

In [32]:
n_features = x.shape[2]
n_features

3

In [49]:
model = Sequential()
#return_sequences: When return_sequences parameter is True, it will output all the hidden states of each time steps
model.add(LSTM(120,activation = 'relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(120, activation = 'relu'))   

model.add(Dense(n_features)) #n-output  
   
model.compile(optimizer='adam',loss='mse')   
model.fit(x, y, epochs=250, verbose=1) #verbose is the choice that how you want to see the output of your Nural Network while it's training

Epoch 1/250
1/1 [==============================] - 3s 3s/step - loss: 4522.5688
Epoch 2/250
1/1 [==============================] - 0s 13ms/step - loss: 4399.5908
Epoch 3/250
1/1 [==============================] - 0s 27ms/step - loss: 4258.5923
Epoch 4/250
1/1 [==============================] - 0s 16ms/step - loss: 4090.4587
Epoch 5/250
1/1 [==============================] - 0s 16ms/step - loss: 3892.6885
Epoch 6/250
1/1 [==============================] - 0s 16ms/step - loss: 3661.7197
Epoch 7/250
1/1 [==============================] - 0s 16ms/step - loss: 3397.6025
Epoch 8/250
1/1 [==============================] - 0s 17ms/step - loss: 3096.4014
Epoch 9/250
1/1 [==============================] - 0s 18ms/step - loss: 2751.6033
Epoch 10/250
1/1 [==============================] - 0s 19ms/step - loss: 2362.1360
Epoch 11/250
1/1 [==============================] - 0s 16ms/step - loss: 1932.4476
Epoch 12/250
1/1 [==============================] - 0s 17ms/step - loss: 1467.9453
Epoch 13/250
1/

### testing

In [58]:
x_input = array([[10,10,10],[20,20,20],[30,30,30]])
x_input

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [57]:
x_input = x_input.reshape(1, n_steps, n_features)

yhat = model.predict(x_input,verbose=0) 
print(yhat)

[[39.993465 39.990677 39.99744 ]]
