# Encoder-Decoder(simple) Lstm
## Developer: mehdi sahraei
### Importing

In [42]:
from numpy import array
from numpy import hstack
from keras.models import  Sequential
from keras.layers import LSTM, Dense, TimeDistributed, RepeatVector

### method

In [44]:
def split_sequence(sequence, n_step_in, n_step_out):
   x,y = list(), list() #x is data and y is label
   for i in range(len(sequence)):
       end_ix = i + n_step_in #timestep
       out_end_ix = end_ix + n_step_out # n-output
       if out_end_ix > len(sequence): #In this -if- we want if data be beyond len(sequence) , the command will not continue and break.
          break
       seq_x, seq_y = sequence[i:end_ix] , sequence[end_ix:out_end_ix]   
       x.append(seq_x)
       y.append(seq_y)
   return array(x) , array(y)

In [37]:
n_step_in, n_step_out = 3 , 2   
seq = [10,20,35,50,55,64,70,80,95]
      
x,y = split_sequence(seq, n_step_in, n_step_out)
print(x.shape,y.shape)   
   
for i in range(len(x)):
   print(x[i],y[i])

(5, 3) (5, 2)
[10 20 35] [50 55]
[20 35 50] [55 64]
[35 50 55] [64 70]
[50 55 64] [70 80]
[55 64 70] [80 95]


In [ ]:
x.shape

### training model

In [48]:
#The input must be three-dimensional or three-channel, that's why we reshape it
n_features = 1
x = x.reshape(x.shape[0],x.shape[1],n_features)    
y = y.reshape(y.shape[0],y.shape[1],n_features)

In [51]:
#stack lstm
model = Sequential()
model.add(LSTM(100,activation = 'relu',input_shape=(n_step_in,n_features)))   
model.add(RepeatVector(n_step_out))   
model.add(LSTM(50,activation = 'relu',return_sequences=True))   
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam',loss='mse')   
model.fit(x,y,epochs=200,verbose=1)

Epoch 1/200
1/1 [==============================] - 3s 3s/step - loss: 4857.0483
Epoch 2/200
1/1 [==============================] - 0s 15ms/step - loss: 4818.6475
Epoch 3/200
1/1 [==============================] - 0s 15ms/step - loss: 4778.2798
Epoch 4/200
1/1 [==============================] - 0s 13ms/step - loss: 4735.2290
Epoch 5/200
1/1 [==============================] - 0s 14ms/step - loss: 4687.5498
Epoch 6/200
1/1 [==============================] - 0s 18ms/step - loss: 4632.7310
Epoch 7/200
1/1 [==============================] - 0s 18ms/step - loss: 4570.2236
Epoch 8/200
1/1 [==============================] - 0s 15ms/step - loss: 4498.6494
Epoch 9/200
1/1 [==============================] - 0s 16ms/step - loss: 4417.4653
Epoch 10/200
1/1 [==============================] - 0s 13ms/step - loss: 4325.9897
Epoch 11/200
1/1 [==============================] - 0s 14ms/step - loss: 4223.5596
Epoch 12/200
1/1 [==============================] - 0s 13ms/step - loss: 4107.3096
Epoch 13/200
1/

### testing

In [57]:
x_input = array([10,20,35])
x_input = x_input.reshape(1, n_step_in, n_features)
x_input.shape

(1, 3, 1)

In [60]:
yhat = model.predict(x_input,verbose=0)
print(yhat,'\n')
print(y[0])

[[[49.83083]
  [55.23344]]] 

[[50]
 [55]]
